# Site settings
title: Gorilla-Studios Photography
email: chris@gorilla-studios.com
description: "Gorilla-Studios Photography"
baseurl: ""
url: "http://www.gorilla-studios.com"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: /_sass
